BEGIN TRAN
	--SHOULD RETURN TWO ROWS GENERATED IN CREATE TABLE SCRIPT
	SELECT *
	FROM TemporalSample
	FOR SYSTEM_TIME ALL
	
	UPDATE TemporalSample
	SET Txt='2';
	WAITFOR DELAY '00:00:01';
	
	UPDATE TemporalSample
	SET Txt='3';
	WAITFOR DELAY '00:00:01';
	
	UPDATE TemporalSample
	SET Txt='4';
	WAITFOR DELAY '00:00:01';
	
	UPDATE TemporalSample
	SET Txt='5';
	WAITFOR DELAY '00:00:01';
	
	--SHOULD RETURN 3 ROWS--
	SELECT *
	FROM TemporalSample
	FOR SYSTEM_TIME ALL

	--SHOULD RETURN 5 ROWS--
	SELECT *
	FROM TemporalSampleHistory
ROLLBACK